cms_label : 'Preliminary'  # appears next to 'CMS' on top of plot
normalized : False
#normalized: True 
log_scale : True 
log_scale_x : False
log_scale_eff : False
use_xlims : True
module : "default"
dataset_axis_handling: "overlaid"
use_variable_binning: False
visualize_cuts: True

dataset_titles:
    '2024F': '2024F'
    '2024G': '2024G'
    '2024H': '2024H'
    '2024I': '2024I'
    '2024F_10': '10% 2024F'
    '2024G_10': '10% 2024G'
    '2024H_10': '10% 2024H'
    '2024I_10': '10% 2024I'
    '2024I_select_runs_test' : '2024I select runs'
    '2024I_select_runs' : '2024I select runs'
    "2024I_386594" : "2024I Run 386594"
    "2024I_386594_test" : "2024I Run 386594"
    "2024I_386924" : "2024I Run 386924"
    "2024I_386924_test" : "2024I Run 386924"

trigger_labels:
    'all_available_triggers' : 'All triggers'
    'all_l1triggers' : 'All L1 triggers'
    'DST_PFScouting_AXOLoose' : 'AXO Loose'
    'DST_PFScouting_AXONominal' : 'AXOL1TL V4 Medium'
    'DST_PFScouting_AXOTight' : 'AXO Tight'
    'DST_PFScouting_AXOVLoose' : ' AXO VLoose'
    'DST_PFScouting_AXOVTight' : 'AXOL1TL V4 Very Tight'
    'DST_PFScouting_CICADALoose' : 'CICADA Loose'
    'DST_PFScouting_CICADAMedium' : 'CICADA Medium'
    'DST_PFScouting_CICADATight' : ' CICADA Tight'
    'DST_PFScouting_CICADAVLoose' : 'CICADA VLoose'
    'DST_PFScouting_CICADAVTight' : 'CICADA VTight'
    'DST_PFScouting_DoubleMuon' : 'Double Muon'
    'DST_PFScouting_SingleMuon' : 'Single Muon'
    'DST_PFScouting_DoubleEG' : 'Double EGamma'
    'DST_PFScouting_JetHT' : 'Jet HT'
    'DST_PFScouting_ZeroBias' : 'Zero Bias'
    'pure_L1_DST_PFScouting_AXONominal' : 'AXO Medium pure w.r.t. L1'
    'pure_L1_DST_PFScouting_CICADAMedium' : 'CICADA Medium pure w.r.t. L1'
    'DST_PFScouting_ZeroBias_DST_PFScouting_AXONominal': 'Zero Bias & AXO Medium'
    'DST_PFScouting_ZeroBias_DST_PFScouting_CICADAMedium': 'Zero Bias & CICADA Medium'

label_templates:
    'totals': # histograms to make per event
        'axo_score': 'AXOL1TL Anomaly Score ({})'
        'cicada_score': 'CICADA Anomaly Score ({})'
        'ht': '$H_T$ [GeV]'
        'met': '$p^{miss}_{T}$ [GeV]'
        'mult': 'Total Object Multiplicity'
        'pt': 'Total Object $p_T$ [GeV]'
    'object_type': # histograms by object type, e.g. total L1 jet multiplicity & pT of all L1 jets in event
        'nScoutingPrimaryVertex': 'Number of Scouting Primary Vertices'
        'ht': '${}$ $\sum p_T$ [GeV]'
        'mult': 'Number of ${}$s'
        'pt': '${}$ $p_T$ [GeV]'
        'eta': '${}$ $\eta$'
        'phi': '${}$ $\phi$'
        'hOverE': '${}$ $H/E$'
        'sigmaIetaIeta': '${}$ $\sigma_{{i\eta i\eta}}$'
        'dPhiIn': '${}$ $\Delta \phi_{{in}}$'
        'dEtaIn': '${}$ $\Delta \eta_{{in}}$'
        'IEOverE': '${}$ $I_E/E$'
        'ITOverE': '${}$ $I_T/E$'
        'IHOverE': '${}$ $I_H/E$'
    'object': # histograms by object type, pt ordered, e.g. pT of leading and subleading jets
        'pt': '${}$ ${}$ $p_T$ [GeV]'
        'eta': '${}$ ${}$ $\eta$'
        'phi': '${}$ ${}$ $\phi$'
    'diobject':
        'mass':   '$m({},{})$ [GeV]'
        'pt':     '$p_{{T}}({},{})$ [GeV]'
        'eta':    '$\eta({},{})$'
        'phi':    '$\phi({},{})$'
        'deltaR': '$\Delta R({},{})$'
        'dphi':   '$\Delta \phi({},{})$'
        'deta':   '$\Delta \eta({},{})$'
        'obj1_pt':  'Leading $p_{{T}}({})$ [GeV]'
        'obj2_pt':  'Sub-leading $p_{{T}}({})$ [GeV]'
        'obj1_eta': 'Leading $\eta({})$'
        'obj2_eta': 'Sub-leading $\eta({})$'
        'obj1_phi': 'Leading $\phi({})$'
        'obj2_phi': 'Sub-leading $\phi({})$'
        'dz': '$\Delta dz({},{})$ [cm]'

object_label_templates:
   'L1Jet': '\text{L1 Jet}'
   'L1EG': '\text{L1 EG}'
   'L1Mu': '\text{L1 }\mu'
   'ScoutingPFJet': '\text{Scouting PF Jet}'
   'ScoutingPFJetRecluster': '\text{Scouting PFRecl. Jet}'
   'ScoutingElectron': '\text{Scouting Electron}'
   'ScoutingMuonNoVtx': '\text{Scouting }\mu_{{\text{no vtx}}}'
   'ScoutingMuonVtx': '\text{Scouting }\mu'
   'ScoutingPhoton' : '\text{Scouting }\gamma'
   'nScoutingPrimaryVertex' : 'Scouting\ Primary\ Vertice'
   'Jet': 'Jet'
   'Electron': 'e'
   'Muon': '$\mu$ '
   
diobject_mass_labels_ROOT:
   'ScoutingElectron_ScoutingElectron': 'm_{ee} [GeV]' 
   'ScoutingPFJetRecluster_ScoutingPFJetRecluster': 'm_{jj} [GeV]' 
   'ScoutingMuonVtx_ScoutingMuonVtx': 'm_{#mu#mu} [GeV]' 
   'ScoutingElectron_ScoutingMuonVtx': 'm_{e#mu} [GeV]'
   'ScoutingPFJetRecluster_ScoutingElectron': 'm_{je} [GeV]'
   'ScoutingPFJetRecluster_ScoutingMuonVtx': 'm_{j#mu} [GeV]'
   'ScoutingPhoton_ScoutingPhoton': 'm_{#gamma#gamma} [GeV]'
   
diobject_mass_labels_mpl:
   'ScoutingElectron_ScoutingElectron': '$m_{ee}$ [GeV]' 
   'ScoutingPFJetRecluster_ScoutingPFJetRecluster': '$m_{jj}$ [GeV]' 
   'ScoutingMuonVtx_ScoutingMuonVtx': '$m_{\mu\mu}$ [GeV]' 
   'ScoutingElectron_ScoutingMuonVtx': '$m_{e\mu}$ [GeV]'
   'ScoutingPFJetRecluster_ScoutingElectron': '$m_{je}$ [GeV]'
   'ScoutingPFJetRecluster_ScoutingMuonVtx': '$m_{j\mu}$ [GeV]'
   'ScoutingPhoton_ScoutingPhoton': '$m_{\gamma\gamma}$ [GeV]'
   'ScoutingElectron_ScoutingPhoton': '$m_{e\gamma}$ [GeV]'
   'ScoutingMuonVtx_ScoutingPhoton': '$m_{\mu\gamma}$ [GeV]'
   'ScoutingPFJetRecluster_ScoutingPhoton': '$m_{j\gamma}$ [GeV]'

object_level:
    'l1':
       - 'L1Jet'
       - 'L1EG'
       - 'L1Mu'
    'scouting':
       - 'ScoutingPFJet'
       - 'ScoutingPFJetRecluster'
       - 'ScoutingElectron'
       - 'ScoutingMuonNoVtx'
       - 'ScoutingMuonVtx'
       - 'ScoutingPhoton' 
       - 'nScoutingPrimaryVertex'
    'full_reco':
       - 'Jet'
       - 'Electron'
       - 'Muon'

rebin:
    "anomaly_score" : 10
    "axo_score_v3" : 10
    "axo_score_v4" : 10
    "cicada_score" : 2
    "ScoutingMuonVtx_ScoutingMuonVtx_mass" : 3
    "l1_ht": 5
    "l1_met": 1
    
rebin_auto:
    "bin_content_min": 10
    "rebin_factor_jump": 5
    "rebin_factor_min": 2
    "rebin_factor_max": 50

xlims:
    "l1_ht": [0,2000] # GeV
    "l1_met": [0,100] # GeV
    "axo_score_v3" : [0,2000]
    "axo_score_v4" : [0,1000]
    "cicada_score_2024" : [0,160]
    "cicada_score_2025" : [0,160]